### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [MsRandom/WorldOfWonder#13] opened 2020-08-30 17:04 UTC
`Minecraft v1.15.2`
`Forge v31.2.36`
`World of Wonder v1.1.1`

After updating this mod to the newest version, my server now crashes on launch.
[Crash Report](https://gist.github.com/WenXin20/bed34b374e17ecf4a59c51d1671e3545)

**Comment by MsRandom** [comment] 2020-08-30 17:31
I couldn't reproduce the exact crash report you got. However I did fix a server startup issue which may be related, we'll release a version 1.1.2 soon and you could test if that fixes it, if not it may be an incompatibility with another mod.

**Comment by WenXin20** [comment] 2020-08-30 18:23
Thanks! I'll give it a try.

**Comment by MsRandom** [comment] 2020-08-30 18:24
No problem! Hopefully it works.

**Comment by WenXin20** [comment] 2020-08-30 18:34
I still got the same crash unfortunately, maybe it crashes when Quark/Quark Oddities is installed?
[Crash Report](https://gist.github.com/WenXin20/2d6ea586a9a86a8186050ffee8521911)

**Comment by MsRandom** [comment] 2020-08-30 18:35
Oh. That would make sense, I forgot to test with the quark compatibility enabled.
This will be fixed shortly.

**Comment by MsRandom** [comment] 2020-08-30 18:47
Version 1.1.3 will be uploaded soon, that will have the crash fully fixed.

**Closed** 2020-08-30 18:46 UTC
Labels: bug

**Comment by WenXin20** [comment] 2020-08-30 18:47
Thanks!
